- name: export game
  id: export
  uses: firebelley/godot-export@master
  with:
      godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
      godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
      relative_project_path: . # build the godot 4 project
      relative_export_path: ./build/destination # move export output to this directory relative to git root
      archive_output: true
      wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
